language: scala
scala:
  - 2.10.0
jdk:
  - openjdk7
  - oraclejdk7
install: /bin/true # always succeeds
script: mvn -e -B -Dbenchmark.poolSize=10 -Dbenchmark.executorServiceType=fixed-thread-pool test -Ptravis


